import Head from "next/head";
import Image from "next/image";
import HomeStyles from "../styles/home.module.scss";
import Layout from "../components/layout";
import Hero from "../components/hero";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={HomeStyles.main}>
        <Hero />
      </main>
    </Layout>
  );
}
